// Data Provinsi dan Kota/Kabupaten di Indonesia
const indonesiaData = {
    "DKI Jakarta": [
        "Jakarta Pusat",
        "Jakarta Utara",
        "Jakarta Barat",
        "Jakarta Selatan",
        "Jakarta Timur",
        "Kepulauan Seribu"
    ],
    "Jawa Barat": [
        "Bandung",
        "Bekasi",
        "Bogor",
        "Cimahi",
        "Cirebon",
        "Depok",
        "Sukabumi",
        "Tasikmalaya",
        "Banjar",
        "Bandung Barat",
        "Ciamis",
        "Cianjur",
        "Garut",
        "Indramayu",
        "Karawang",
        "Kuningan",
        "Majalengka",
        "Pangandaran",
        "Purwakarta",
        "Subang",
        "Sumedang"
    ],
    "Jawa Tengah": [
        "Magelang",
        "Pekalongan",
        "Salatiga",
        "Semarang",
        "Surakarta",
        "Tegal",
        "Banjarnegara",
        "Banyumas",
        "Batang",
        "Blora",
        "Boyolali",
        "Brebes",
        "Cilacap",
        "Demak",
        "Grobogan",
        "Jepara",
        "Karanganyar",
        "Kebumen",
        "Kendal",
        "Klaten",
        "Kudus",
        "Magelang",
        "Pati",
        "Pekalongan",
        "Pemalang",
        "Purbalingga",
        "Purworejo",
        "Rembang",
        "Semarang",
        "Sragen",
        "Sukoharjo",
        "Tegal",
        "Temanggung",
        "Wonogiri",
        "Wonosobo"
    ],
    "DI Yogyakarta": [
        "Yogyakarta",
        "Bantul",
        "Gunungkidul",
        "Kulon Progo",
        "Sleman"
    ],
    "Jawa Timur": [
        "Batu",
        "Blitar",
        "Kediri",
        "Madiun",
        "Malang",
        "Mojokerto",
        "Pasuruan",
        "Probolinggo",
        "Surabaya",
        "Bangkalan",
        "Banyuwangi",
        "Blitar",
        "Bojonegoro",
        "Bondowoso",
        "Gresik",
        "Jember",
        "Jombang",
        "Kediri",
        "Lamongan",
        "Lumajang",
        "Madiun",
        "Magetan",
        "Malang",
        "Mojokerto",
        "Nganjuk",
        "Ngawi",
        "Pacitan",
        "Pamekasan",
        "Pasuruan",
        "Ponorogo",
        "Probolinggo",
        "Sampang",
        "Sidoarjo",
        "Situbondo",
        "Sumenep",
        "Trenggalek",
        "Tuban",
        "Tulungagung"
    ],
    "Banten": [
        "Cilegon",
        "Serang",
        "Tangerang Selatan",
        "Tangerang",
        "Lebak",
        "Pandeglang",
        "Serang"
    ],
    "Bali": [
        "Denpasar",
        "Badung",
        "Bangli",
        "Buleleng",
        "Gianyar",
        "Jembrana",
        "Karangasem",
        "Klungkung",
        "Tabanan"
    ],
    "Nusa Tenggara Barat": [
        "Bima",
        "Mataram",
        "Bima",
        "Dompu",
        "Lombok Barat",
        "Lombok Tengah",
        "Lombok Timur",
        "Lombok Utara",
        "Sumbawa",
        "Sumbawa Barat"
    ],
    "Nusa Tenggara Timur": [
        "Kupang",
        "Alor",
        "Belu",
        "Ende",
        "Flores Timur",
        "Kupang",
        "Lembata",
        "Manggarai",
        "Manggarai Barat",
        "Manggarai Timur",
        "Nagekeo",
        "Ngada",
        "Rote Ndao",
        "Sabu Raijua",
        "Sikka",
        "Sumba Barat",
        "Sumba Barat Daya",
        "Sumba Tengah",
        "Sumba Timur",
        "Timor Tengah Selatan",
        "Timor Tengah Utara"
    ],
    "Kalimantan Barat": [
        "Pontianak",
        "Singkawang",
        "Bengkayang",
        "Kapuas Hulu",
        "Kayong Utara",
        "Ketapang",
        "Kubu Raya",
        "Landak",
        "Melawi",
        "Mempawah",
        "Sambas",
        "Sanggau",
        "Sekadau",
        "Sintang"
    ],
    "Kalimantan Tengah": [
        "Palangka Raya",
        "Barito Selatan",
        "Barito Timur",
        "Barito Utara",
        "Gunung Mas",
        "Kapuas",
        "Katingan",
        "Kotawaringin Barat",
        "Kotawaringin Timur",
        "Lamandau",
        "Murung Raya",
        "Pulang Pisau",
        "Sukamara",
        "Seruyan"
    ],
    "Kalimantan Selatan": [
        "Banjarbaru",
        "Banjarmasin",
        "Balangan",
        "Banjar",
        "Barito Kuala",
        "Hulu Sungai Selatan",
        "Hulu Sungai Tengah",
        "Hulu Sungai Utara",
        "Kotabaru",
        "Tabalong",
        "Tanah Bumbu",
        "Tanah Laut",
        "Tapin"
    ],
    "Kalimantan Timur": [
        "Balikpapan",
        "Bontang",
        "Samarinda",
        "Berau",
        "Kutai Barat",
        "Kutai Kartanegara",
        "Kutai Timur",
        "Mahakam Ulu",
        "Paser",
        "Penajam Paser Utara"
    ],
    "Kalimantan Utara": [
        "Tarakan",
        "Bulungan",
        "Malinau",
        "Nunukan",
        "Tana Tidung"
    ],
    "Sulawesi Utara": [
        "Bitung",
        "Kotamobagu",
        "Manado",
        "Tomohon",
        "Bolaang Mongondow",
        "Bolaang Mongondow Selatan",
        "Bolaang Mongondow Timur",
        "Bolaang Mongondow Utara",
        "Kepulauan Sangihe",
        "Kepulauan Siau Tagulandang Biaro",
        "Kepulauan Talaud",
        "Minahasa",
        "Minahasa Selatan",
        "Minahasa Tenggara",
        "Minahasa Utara"
    ],
    "Sulawesi Tengah": [
        "Palu",
        "Banggai",
        "Banggai Kepulauan",
        "Banggai Laut",
        "Buol",
        "Donggala",
        "Morowali",
        "Morowali Utara",
        "Parigi Moutong",
        "Poso",
        "Sigi",
        "Tojo Una-Una",
        "Toli-Toli"
    ],
    "Sulawesi Selatan": [
        "Makassar",
        "Palopo",
        "Parepare",
        "Bantaeng",
        "Barru",
        "Bone",
        "Bulukumba",
        "Enrekang",
        "Gowa",
        "Jeneponto",
        "Kepulauan Selayar",
        "Luwu",
        "Luwu Timur",
        "Luwu Utara",
        "Maros",
        "Pangkajene dan Kepulauan",
        "Pinrang",
        "Sidenreng Rappang",
        "Sinjai",
        "Soppeng",
        "Takalar",
        "Tana Toraja",
        "Toraja Utara",
        "Wajo"
    ],
    "Sulawesi Tenggara": [
        "Bau-Bau",
        "Kendari",
        "Bombana",
        "Buton",
        "Buton Selatan",
        "Buton Tengah",
        "Buton Utara",
        "Kolaka",
        "Kolaka Timur",
        "Kolaka Utara",
        "Konawe",
        "Konawe Kepulauan",
        "Konawe Selatan",
        "Konawe Utara",
        "Muna",
        "Muna Barat",
        "Wakatobi"
    ],
    "Gorontalo": [
        "Gorontalo",
        "Boalemo",
        "Bone Bolango",
        "Gorontalo",
        "Gorontalo Utara",
        "Pohuwato"
    ],
    "Sulawesi Barat": [
        "Majene",
        "Mamasa",
        "Mamuju",
        "Mamuju Tengah",
        "Mamuju Utara",
        "Polewali Mandar"
    ],
    "Maluku": [
        "Ambon",
        "Tual",
        "Buru",
        "Buru Selatan",
        "Kepulauan Aru",
        "Maluku Barat Daya",
        "Maluku Tengah",
        "Maluku Tenggara",
        "Maluku Tenggara Barat",
        "Seram Bagian Barat",
        "Seram Bagian Timur"
    ],
    "Maluku Utara": [
        "Ternate",
        "Tidore Kepulauan",
        "Halmahera Barat",
        "Halmahera Selatan",
        "Halmahera Tengah",
        "Halmahera Timur",
        "Halmahera Utara",
        "Kepulauan Sula",
        "Pulau Morotai",
        "Pulau Taliabu"
    ],
    "Papua": [
        "Jayapura",
        "Asmat",
        "Biak Numfor",
        "Boven Digoel",
        "Deiyai",
        "Dogiyai",
        "Intan Jaya",
        "Jayapura",
        "Jayawijaya",
        "Keerom",
        "Kepulauan Yapen",
        "Lanny Jaya",
        "Mamberamo Raya",
        "Mamberamo Tengah",
        "Mappi",
        "Merauke",
        "Mimika",
        "Nabire",
        "Nduga",
        "Paniai",
        "Pegunungan Bintang",
        "Puncak",
        "Puncak Jaya",
        "Sarmi",
        "Supiori",
        "Tolikara",
        "Waropen",
        "Yahukimo",
        "Yalimo"
    ],
    "Papua Barat": [
        "Sorong",
        "Fakfak",
        "Kaimana",
        "Manokwari",
        "Manokwari Selatan",
        "Maybrat",
        "Pegunungan Arfak",
        "Raja Ampat",
        "Sorong",
        "Sorong Selatan",
        "Tambrauw",
        "Teluk Bintuni",
        "Teluk Wondama"
    ],
    "Aceh": [
        "Banda Aceh",
        "Langsa",
        "Lhokseumawe",
        "Sabang",
        "Subulussalam",
        "Aceh Barat",
        "Aceh Barat Daya",
        "Aceh Besar",
        "Aceh Jaya",
        "Aceh Selatan",
        "Aceh Singkil",
        "Aceh Tamiang",
        "Aceh Tengah",
        "Aceh Tenggara",
        "Aceh Timur",
        "Aceh Utara",
        "Bener Meriah",
        "Bireuen",
        "Gayo Lues",
        "Nagan Raya",
        "Pidie",
        "Pidie Jaya",
        "Simeulue"
    ],
    "Sumatera Utara": [
        "Binjai",
        "Gunungsitoli",
        "Medan",
        "Padang Sidempuan",
        "Pematangsiantar",
        "Sibolga",
        "Tanjungbalai",
        "Tebing Tinggi",
        "Asahan",
        "Batubara",
        "Dairi",
        "Deli Serdang",
        "Humbang Hasundutan",
        "Karo",
        "Labuhanbatu",
        "Labuhanbatu Selatan",
        "Labuhanbatu Utara",
        "Langkat",
        "Mandailing Natal",
        "Nias",
        "Nias Barat",
        "Nias Selatan",
        "Nias Utara",
        "Padang Lawas",
        "Padang Lawas Utara",
        "Pakpak Bharat",
        "Samosir",
        "Serdang Bedagai",
        "Simalungun",
        "Tapanuli Selatan",
        "Tapanuli Tengah",
        "Tapanuli Utara",
        "Toba Samosir"
    ],
    "Sumatera Barat": [
        "Bukittinggi",
        "Padang",
        "Padangpanjang",
        "Pariaman",
        "Payakumbuh",
        "Sawahlunto",
        "Solok",
        "Agam",
        "Dharmasraya",
        "Kepulauan Mentawai",
        "Lima Puluh Kota",
        "Padang Pariaman",
        "Pasaman",
        "Pasaman Barat",
        "Pesisir Selatan",
        "Sijunjung",
        "Solok",
        "Solok Selatan",
        "Tanah Datar"
    ],
    "Riau": [
        "Dumai",
        "Pekanbaru",
        "Bengkalis",
        "Indragiri Hilir",
        "Indragiri Hulu",
        "Kampar",
        "Kepulauan Meranti",
        "Kuantan Singingi",
        "Pelalawan",
        "Rokan Hilir",
        "Rokan Hulu",
        "Siak"
    ],
    "Jambi": [
        "Jambi",
        "Sungai Penuh",
        "Batang Hari",
        "Bungo",
        "Kerinci",
        "Merangin",
        "Muaro Jambi",
        "Sarolangun",
        "Tanjung Jabung Barat",
        "Tanjung Jabung Timur",
        "Tebo"
    ],
    "Sumatera Selatan": [
        "Lubuklinggau",
        "Pagar Alam",
        "Palembang",
        "Prabumulih",
        "Banyuasin",
        "Empat Lawang",
        "Lahat",
        "Muara Enim",
        "Musi Banyuasin",
        "Musi Rawas",
        "Musi Rawas Utara",
        "Ogan Ilir",
        "Ogan Komering Ilir",
        "Ogan Komering Ulu",
        "Ogan Komering Ulu Selatan",
        "Ogan Komering Ulu Timur",
        "Penukal Abab Lematang Ilir"
    ],
    "Bengkulu": [
        "Bengkulu",
        "Bengkulu Selatan",
        "Bengkulu Tengah",
        "Bengkulu Utara",
        "Kaur",
        "Kepahiang",
        "Lebong",
        "Mukomuko",
        "Rejang Lebong",
        "Seluma"
    ],
    "Lampung": [
        "Bandar Lampung",
        "Metro",
        "Lampung Barat",
        "Lampung Selatan",
        "Lampung Tengah",
        "Lampung Timur",
        "Lampung Utara",
        "Mesuji",
        "Pesawaran",
        "Pesisir Barat",
        "Pringsewu",
        "Tanggamus",
        "Tulang Bawang",
        "Tulang Bawang Barat",
        "Way Kanan"
    ],
    "Kepulauan Bangka Belitung": [
        "Pangkalpinang",
        "Bangka",
        "Bangka Barat",
        "Bangka Selatan",
        "Bangka Tengah",
        "Belitung",
        "Belitung Timur"
    ],
    "Kepulauan Riau": [
        "Batam",
        "Tanjungpinang",
        "Bintan",
        "Karimun",
        "Kepulauan Anambas",
        "Lingga",
        "Natuna"
    ]
};

// Load provinsi ke dropdown
function loadProvinsi() {
    const select = document.getElementById('provinsiSelect');
    
    if (!select) return;
    
    // Clear existing options except first
    select.innerHTML = '<option value="">-- Pilih Provinsi --</option>';
    
    // Sort provinsi alphabetically
    const sortedProvinsi = Object.keys(indonesiaData).sort();
    
    sortedProvinsi.forEach(provinsi => {
        const option = document.createElement('option');
        option.value = provinsi;
        option.textContent = provinsi;
        select.appendChild(option);
    });
}

// Load kota berdasarkan provinsi yang dipilih
function loadKota() {
    const provinsiSelect = document.getElementById('provinsiSelect');
    const kotaSelect = document.getElementById('kotaSelect');
    
    if (!provinsiSelect || !kotaSelect) return;
    
    const selectedProvinsi = provinsiSelect.value;
    
    // Clear kota dropdown
    kotaSelect.innerHTML = '<option value="">-- Pilih Kota --</option>';
    
    if (!selectedProvinsi) {
        kotaSelect.disabled = true;
        return;
    }
    
    kotaSelect.disabled = false;
    
    // Get kota list for selected provinsi
    const kotaList = indonesiaData[selectedProvinsi] || [];
    
    // Sort kota alphabetically
    const sortedKota = kotaList.sort();
    
    sortedKota.forEach(kota => {
        const option = document.createElement('option');
        option.value = kota;
        option.textContent = kota;
        kotaSelect.appendChild(option);
    });
}